/*
Un composant JProgressBar sert d'affichage du thermomètre dont la plage de températures est de -50 à 50.
La fenêtre principale affiche les valeurs numériques de la température extérieure et du thermostat,
 mais ne permet pas de les modifier en saisissant des valeurs.
 */

/*
 * VueThermometre2.java
 *
 * Created on 31 oct. 2012, 05:06:49
 */

package thermostat;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoundedRangeModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author gwendo
 */
public class VueThermometre2 extends javax.swing.JFrame implements BoundedRangeModel,ActionListener {

    
    private Chambre chambre;//definit un modele chambre
    double min = -50;//valeurs min et max du thermometre: du jprogressbar
    double max = 50;

    /** Creates new form VueThermometre2 */
    public VueThermometre2(Chambre c) {
        chambre = c;
        chambre.getTimer().addActionListener(this);//A chaque tick() du timer on appellera notre actionPerformed
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progres = new javax.swing.JProgressBar();
        Thermometre = new java.awt.Label();
        chauffageLabel = new java.awt.Label();
        ChauffageState = new java.awt.Label();
        TempExtLabel = new java.awt.Label();
        TempExtValeur = new java.awt.Label();
        thermostatValeur = new java.awt.Label();
        thermostatLabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Progres.setForeground(new java.awt.Color(239, 20, 20));
        Progres.setMaximum(50);
        Progres.setMinimum(-50);
        Progres.setOrientation(1);
        Progres.setValue(20);
        Progres.setString("20");
        Progres.setStringPainted(true);

        Thermometre.setText("Thermomètre");

        chauffageLabel.setText("Chauffage");

        ChauffageState.setText("Inactif");

        TempExtLabel.setText("Température Extérieure");

        TempExtValeur.setText("0");

        thermostatValeur.setText("20");

        thermostatLabel.setText("Thermostat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Progres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Thermometre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chauffageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                            .addComponent(ChauffageState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(thermostatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                            .addComponent(thermostatValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TempExtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                            .addComponent(TempExtValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(93, 93, 93)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Progres, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thermometre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChauffageState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chauffageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TempExtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TempExtValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(thermostatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thermostatValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */

    /* methods de BoundedRangeModel*/

    public int getMinimum() {
        return (int)min;
    }

    public void setMinimum(int newMinimum) {
        min=newMinimum;
    }

    public int getMaximum() {
        return (int)max;
    }

    public void setMaximum(int newMaximum) {
        max=newMaximum;
    }

    public int getValue() {
         return (int)chambre.getTemperature();
    }

    public void setValue(int newValue) {

    }

    public void setValueIsAdjusting(boolean b) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public boolean getValueIsAdjusting() {
        return true;
    }

    public int getExtent() {
        return 0;
    }

    public void setExtent(int newExtent) {
    }

    public void setRangeProperties(int value, int extent, int min, int max, boolean adjusting) {
    }

    public void addChangeListener(ChangeListener x) {

    }

    public void removeChangeListener(ChangeListener x) {
    }

    //For each timer tick:
    public void actionPerformed(ActionEvent e) {

        //on change l'affichage de la valeur du thermostat sur la fenêtre principale
        Double temperatureIntVal= chambre.getTemperature();
        temperatureIntVal=(double)Math.round(temperatureIntVal*100)/100;
        thermostatValeur.setText( temperatureIntVal.toString());
        //on change la valeur de la temperature exterieure sur la fenêtre principale
        Double tempextVal = chambre.getTemperatureExterieure();
        TempExtValeur.setText(tempextVal.toString());
        //on update la jprogressbar thermometre
        temperatureIntVal=(double)Math.round(temperatureIntVal*100)/100;
        Progres.setValue(temperatureIntVal.intValue());
        Progres.setString(temperatureIntVal.toString());//on affiche dans la progress bar la valeur courante de la temperature interieure
        //si le chauffage est en route on modifie l'affiche de chauffage dans la fenêtre principale à ACTIF
        if(chambre.isChauffage())
        {
            ChauffageState.setText("Actif");
        }
        else
        {
            ChauffageState.setText("Inactif");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label ChauffageState;
    private javax.swing.JProgressBar Progres;
    private java.awt.Label TempExtLabel;
    private java.awt.Label TempExtValeur;
    private java.awt.Label Thermometre;
    private java.awt.Label chauffageLabel;
    private java.awt.Label thermostatLabel;
    private java.awt.Label thermostatValeur;
    // End of variables declaration//GEN-END:variables

}
